### ISSUE TITLE
Implement Random Forests (After Decision trees)

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#7] opened 2020-10-01 14:47 UTC
This issue will be merged only when Decision trees are implemented.
Related Resources one can follow :-
1. https://machinelearningmastery.com/implement-random-forest-scratch-python/
2. https://towardsdatascience.com/building-a-random-forest-classifier-c73a4cae6781

**Comment by thesauravkarmakar** [comment] 2020-10-03 12:55
I would like to try this!

**Comment by TarunTomar122** [comment] 2020-10-03 14:10
@thesauravkarmakar  alright you are assigned to this issue. Keep us  updated and inform in case you face any problems.

**Comment by rohansingh9001** [comment] 2020-10-03 16:01
Decision trees have been added. This issue can be worked upon now.

@thesauravkarmakar typically we want both regression and classification functionality. If you want to implement only one of these, please let us know in advance 😉.

**Comment by thesauravkarmakar** [comment] 2020-10-03 16:03
> Decision trees have been added. This issue can be worked upon now.
> 
> @thesauravkarmakar typically we want both regression and classification functionality. If you want to implement only one of these, please let us know in advance 😉.

So @rohansingh9001  you want me to do Random Forest for Regression and Classification? Right?

**Comment by rohansingh9001** [comment] 2020-10-03 16:14
@thesauravkarmakar You can implement even one if you wish to. Just inform us in that case so that someone else from the institute can work on the model that you are not working on. If you can do both great!

**Comment by thesauravkarmakar** [comment] 2020-10-03 16:18
> @thesauravkarmakar You can implement even one if you wish to. Just inform us in that case so that someone else from the institute can work on the model that you are not working on. If you can do both great!

I can work for Classification if I complete it and there is no one assigned for Regression, maybe I will try to do it.

**Comment by rohansingh9001** [comment] 2020-10-03 20:30
@thesauravkarmakar sure.

As far as I understand Hacktoberfest counts contributions to any public repository as long as your PR is not marked as spam or invalid.

We have labelled issues as Hacktoberfest already so that users can be motivated to contribute. However, the labelling is not necessary. You can correct me if I am wrong but people who have already contributed to the repository have already been considered valid contributors in Hacktoberfest.

As far as labelling the repository with Hacktoberfest goes, I think its a good suggestion. We are currently in the process of writing a proper README and wiki for the repository. Since the repository is mostly organised by Robotics Club IITJ and most of us were engaged in other commitments (Exams😅), the process got delayed. 

However, I will consider it as well as adding other tags when we revamp the repo.

**Comment by thesauravkarmakar** [comment] 2020-10-04 05:01
> @thesauravkarmakar sure.
> 
> As far as I understand Hacktoberfest counts contributions to any public repository as long as your PR is not marked as spam or invalid.
> 
> We have labelled issues as Hacktoberfest already so that users can be motivated to contribute. However, the labelling is not necessary. You can correct me if I am wrong but people who have already contributed to the repository have already been considered valid contributors in Hacktoberfest.
> 
> As far as labelling the repository with Hacktoberfest goes, I think its a good suggestion. We are currently in the process of writing a proper README and wiki for the repository. Since the repository is mostly organised by Robotics Club IITJ and most of us were engaged in other commitments (Exams😅), the process got delayed.
> 
> However, I will consider it as well as adding other tags when we revamp the repo.

You're right. But due to recent spamming, they have added this HacktoberFest Opt-in. Check out this tweet: https://twitter.com/hacktoberfest/status/1312221208667185153?s=20

**Comment by rohansingh9001** [comment] 2020-10-04 05:05
@thesauravkarmakar changes have been made. Any PRs you make on this repository will now count towards Hacktoberfest. Cheers.

**Comment by thesauravkarmakar** [comment] 2020-10-05 15:12
Sorry! @rohansingh9001 I'm quite busy and won't be able to solve this issue

**Comment by rohansingh9001** [comment] 2020-10-05 18:26
@thesauravkarmakar no issues. We will assign it to someone else.

**Comment by TarunTomar122** [comment] 2020-10-21 13:24
Just a heads up im doin this now!

**Comment by kwanit1142** [comment] 2020-10-22 05:53
@TarunTomar122 , please after completing the code, also write docstrings for the same.

**Comment by soumya997** [comment] 2020-11-29 23:02
hey @TarunTomar122 @rohansingh9001 its a great repo, one thing I would like to ask you guys to do if possible.
As the repo is all about implementing an algorithm from scratch so can we make this as a python package. By doing that there will be three benefits **1. people will be able to get their basics clear(the aim of your repo (`This repository gives beginners and newcomers in the field of AI and ML a chance to understand the inner workings of popular learning algorithms` ) + 2. people will be get experience for making a library + 3. the whole work will get some utility which other people will be able to use and get benefits from.**

**Comment by rohansingh9001** [comment] 2020-11-29 23:16
@soumya997 If you see some of the files in our repository, You will see that the repo already has some of the setup files needed to make it a python package, i.e. setup.py.
We will definitely make repo into a python package though there is some time in that. I want to fully polish the repository (or at least partially do so). There are some places here and there where it can still be improved. So till then, we have not uploaded the files on pypi.
Though I hope soon, in 1-2 months, the repository will be much better than it is right now.

**Comment by Prachi0203** [comment] 2020-12-05 06:34
I want to work on this. I am a beginner in open source. Also decision trees is implemented or not?Or it's just random forest.?

**Comment by TarunTomar122** [comment] 2020-12-05 06:46
Hye @Prachi0203. Decision trees are already implemented in our library. You can check that out, the link is in the readme now. In this issue, you are supposed to implement random forest using the already implemented decision trees. I hope that clears all of your doubts. Feel free to ask more. And do keep us updated on your status with this issue.

**Comment by ashwani-rathee** [comment] 2020-12-12 08:57
@rohansingh9001 Has this been assigned to anybody or I can work on this??

**Comment by kwanit1142** [comment] 2021-03-04 05:20
Thanks to @Shreya-IITJ, Finally Closing this issue

**Closed by kwanit1142** 2021-03-04 05:20 UTC
Labels: WOC, medium
